# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapclientplugins\meshgeneratorstep\qt\meshgeneratorwidget.ui'
#
# Created: Fri Dec  4 10:25:58 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MeshGeneratorWidget(object):
    def setupUi(self, MeshGeneratorWidget):
        MeshGeneratorWidget.setObjectName("MeshGeneratorWidget")
        MeshGeneratorWidget.resize(2378, 1472)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MeshGeneratorWidget.sizePolicy().hasHeightForWidth())
        MeshGeneratorWidget.setSizePolicy(sizePolicy)
        MeshGeneratorWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout = QtGui.QHBoxLayout(MeshGeneratorWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget = QtGui.QDockWidget(MeshGeneratorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.identifier_frame = QtGui.QFrame(self.dockWidgetContents)
        self.identifier_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.identifier_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.identifier_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.identifier_frame.setObjectName("identifier_frame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.identifier_frame)
        self.verticalLayout_4.setContentsMargins(0, 5, 0, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.identifier_label = QtGui.QLabel(self.identifier_frame)
        self.identifier_label.setObjectName("identifier_label")
        self.verticalLayout_4.addWidget(self.identifier_label)
        self.verticalLayout.addWidget(self.identifier_frame)
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 705, 813))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scaffoldFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaffoldFrame.sizePolicy().hasHeightForWidth())
        self.scaffoldFrame.setSizePolicy(sizePolicy)
        self.scaffoldFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.scaffoldFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scaffoldFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.scaffoldFrame.setObjectName("scaffoldFrame")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scaffoldFrame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.subscaffold_frame = QtGui.QFrame(self.scaffoldFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subscaffold_frame.sizePolicy().hasHeightForWidth())
        self.subscaffold_frame.setSizePolicy(sizePolicy)
        self.subscaffold_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.subscaffold_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.subscaffold_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.subscaffold_frame.setObjectName("subscaffold_frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.subscaffold_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.subscaffold_label = QtGui.QLabel(self.subscaffold_frame)
        self.subscaffold_label.setObjectName("subscaffold_label")
        self.verticalLayout_5.addWidget(self.subscaffold_label)
        self.subscaffoldBack_pushButton = QtGui.QPushButton(self.subscaffold_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subscaffoldBack_pushButton.sizePolicy().hasHeightForWidth())
        self.subscaffoldBack_pushButton.setSizePolicy(sizePolicy)
        self.subscaffoldBack_pushButton.setObjectName("subscaffoldBack_pushButton")
        self.verticalLayout_5.addWidget(self.subscaffoldBack_pushButton)
        self.verticalLayout_8.addWidget(self.subscaffold_frame)
        self.meshType_frame = QtGui.QFrame(self.scaffoldFrame)
        self.meshType_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.meshType_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.meshType_frame.setObjectName("meshType_frame")
        self.formLayout = QtGui.QFormLayout(self.meshType_frame)
        self.formLayout.setContentsMargins(0, -1, 0, -1)
        self.formLayout.setObjectName("formLayout")
        self.meshType_label = QtGui.QLabel(self.meshType_frame)
        self.meshType_label.setObjectName("meshType_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.meshType_label)
        self.meshType_comboBox = QtGui.QComboBox(self.meshType_frame)
        self.meshType_comboBox.setObjectName("meshType_comboBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.meshType_comboBox)
        self.parameterSet_label = QtGui.QLabel(self.meshType_frame)
        self.parameterSet_label.setObjectName("parameterSet_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.parameterSet_label)
        self.parameterSet_comboBox = QtGui.QComboBox(self.meshType_frame)
        self.parameterSet_comboBox.setObjectName("parameterSet_comboBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.parameterSet_comboBox)
        self.verticalLayout_8.addWidget(self.meshType_frame)
        self.meshTypeOptions_frame = QtGui.QFrame(self.scaffoldFrame)
        self.meshTypeOptions_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.meshTypeOptions_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.meshTypeOptions_frame.setObjectName("meshTypeOptions_frame")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.meshTypeOptions_frame)
        self.verticalLayout_9.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8.addWidget(self.meshTypeOptions_frame)
        self.scaffoldFrame_line_1 = QtGui.QFrame(self.scaffoldFrame)
        self.scaffoldFrame_line_1.setFrameShape(QtGui.QFrame.HLine)
        self.scaffoldFrame_line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.scaffoldFrame_line_1.setObjectName("scaffoldFrame_line_1")
        self.verticalLayout_8.addWidget(self.scaffoldFrame_line_1)
        self.modifyOptions_frame = QtGui.QFrame(self.scaffoldFrame)
        self.modifyOptions_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.modifyOptions_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.modifyOptions_frame.setObjectName("modifyOptions_frame")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.modifyOptions_frame)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.deleteElementsRanges_frame = QtGui.QFrame(self.modifyOptions_frame)
        self.deleteElementsRanges_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.deleteElementsRanges_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.deleteElementsRanges_frame.setObjectName("deleteElementsRanges_frame")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.deleteElementsRanges_frame)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.deleteElementsRanges_label = QtGui.QLabel(self.deleteElementsRanges_frame)
        self.deleteElementsRanges_label.setObjectName("deleteElementsRanges_label")
        self.verticalLayout_10.addWidget(self.deleteElementsRanges_label)
        self.deleteElementsRanges_lineEdit = QtGui.QLineEdit(self.deleteElementsRanges_frame)
        self.deleteElementsRanges_lineEdit.setObjectName("deleteElementsRanges_lineEdit")
        self.verticalLayout_10.addWidget(self.deleteElementsRanges_lineEdit)
        self.deleteElementsSelection_pushButton = QtGui.QPushButton(self.deleteElementsRanges_frame)
        self.deleteElementsSelection_pushButton.setObjectName("deleteElementsSelection_pushButton")
        self.verticalLayout_10.addWidget(self.deleteElementsSelection_pushButton)
        self.verticalLayout_6.addWidget(self.deleteElementsRanges_frame)
        self.rotation_label = QtGui.QLabel(self.modifyOptions_frame)
        self.rotation_label.setObjectName("rotation_label")
        self.verticalLayout_6.addWidget(self.rotation_label)
        self.rotation_lineEdit = QtGui.QLineEdit(self.modifyOptions_frame)
        self.rotation_lineEdit.setObjectName("rotation_lineEdit")
        self.verticalLayout_6.addWidget(self.rotation_lineEdit)
        self.scale_label = QtGui.QLabel(self.modifyOptions_frame)
        self.scale_label.setObjectName("scale_label")
        self.verticalLayout_6.addWidget(self.scale_label)
        self.scale_lineEdit = QtGui.QLineEdit(self.modifyOptions_frame)
        self.scale_lineEdit.setObjectName("scale_lineEdit")
        self.verticalLayout_6.addWidget(self.scale_lineEdit)
        self.translation_label = QtGui.QLabel(self.modifyOptions_frame)
        self.translation_label.setObjectName("translation_label")
        self.verticalLayout_6.addWidget(self.translation_label)
        self.translation_lineEdit = QtGui.QLineEdit(self.modifyOptions_frame)
        self.translation_lineEdit.setObjectName("translation_lineEdit")
        self.verticalLayout_6.addWidget(self.translation_lineEdit)
        self.applyTransformation_pushButton = QtGui.QPushButton(self.modifyOptions_frame)
        self.applyTransformation_pushButton.setObjectName("applyTransformation_pushButton")
        self.verticalLayout_6.addWidget(self.applyTransformation_pushButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout_8.addWidget(self.modifyOptions_frame)
        self.verticalLayout_3.addWidget(self.scaffoldFrame)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.controls_tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controls_tabWidget.sizePolicy().hasHeightForWidth())
        self.controls_tabWidget.setSizePolicy(sizePolicy)
        self.controls_tabWidget.setObjectName("controls_tabWidget")
        self.display_tab = QtGui.QWidget()
        self.display_tab.setObjectName("display_tab")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.display_tab)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.displayData_frame = QtGui.QFrame(self.display_tab)
        self.displayData_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayData_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayData_frame.setObjectName("displayData_frame")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.displayData_frame)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.displayDataPoints_frame = QtGui.QFrame(self.displayData_frame)
        self.displayDataPoints_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayDataPoints_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayDataPoints_frame.setObjectName("displayDataPoints_frame")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.displayDataPoints_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.displayDataPoints_checkBox = QtGui.QCheckBox(self.displayDataPoints_frame)
        self.displayDataPoints_checkBox.setObjectName("displayDataPoints_checkBox")
        self.horizontalLayout_9.addWidget(self.displayDataPoints_checkBox)
        self.displayDataContours_checkBox = QtGui.QCheckBox(self.displayDataPoints_frame)
        self.displayDataContours_checkBox.setObjectName("displayDataContours_checkBox")
        self.horizontalLayout_9.addWidget(self.displayDataContours_checkBox)
        self.displayDataRadius_checkBox = QtGui.QCheckBox(self.displayDataPoints_frame)
        self.displayDataRadius_checkBox.setObjectName("displayDataRadius_checkBox")
        self.horizontalLayout_9.addWidget(self.displayDataRadius_checkBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_11.addWidget(self.displayDataPoints_frame)
        self.displayDataMarkers_frame = QtGui.QFrame(self.displayData_frame)
        self.displayDataMarkers_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayDataMarkers_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayDataMarkers_frame.setObjectName("displayDataMarkers_frame")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.displayDataMarkers_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.displayDataMarkerPoints_checkBox = QtGui.QCheckBox(self.displayDataMarkers_frame)
        self.displayDataMarkerPoints_checkBox.setObjectName("displayDataMarkerPoints_checkBox")
        self.horizontalLayout_10.addWidget(self.displayDataMarkerPoints_checkBox)
        self.displayDataMarkerNames_checkBox = QtGui.QCheckBox(self.displayDataMarkers_frame)
        self.displayDataMarkerNames_checkBox.setObjectName("displayDataMarkerNames_checkBox")
        self.horizontalLayout_10.addWidget(self.displayDataMarkerNames_checkBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_11.addWidget(self.displayDataMarkers_frame)
        self.verticalLayout_13.addWidget(self.displayData_frame)
        self.displayNodes_frame = QtGui.QFrame(self.display_tab)
        self.displayNodes_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayNodes_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayNodes_frame.setObjectName("displayNodes_frame")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.displayNodes_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.displayNodePoints_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        self.displayNodePoints_checkBox.setObjectName("displayNodePoints_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodePoints_checkBox)
        self.displayNodeNumbers_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeNumbers_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeNumbers_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeNumbers_checkBox.setObjectName("displayNodeNumbers_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodeNumbers_checkBox)
        self.displayNodeDerivatives_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivatives_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivatives_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivatives_checkBox.setObjectName("displayNodeDerivatives_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodeDerivatives_checkBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_13.addWidget(self.displayNodes_frame)
        self.displayNodeDerivativeLabels_frame = QtGui.QFrame(self.display_tab)
        self.displayNodeDerivativeLabels_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayNodeDerivativeLabels_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayNodeDerivativeLabels_frame.setObjectName("displayNodeDerivativeLabels_frame")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.displayNodeDerivativeLabels_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.displayNodeDerivativeLabelsD1_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD1_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD1_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD1_checkBox.setObjectName("displayNodeDerivativeLabelsD1_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD1_checkBox)
        self.displayNodeDerivativeLabelsD2_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD2_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD2_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD2_checkBox.setObjectName("displayNodeDerivativeLabelsD2_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD2_checkBox)
        self.displayNodeDerivativeLabelsD3_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD3_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD3_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD3_checkBox.setObjectName("displayNodeDerivativeLabelsD3_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD3_checkBox)
        self.displayNodeDerivativeLabelsD12_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD12_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD12_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD12_checkBox.setObjectName("displayNodeDerivativeLabelsD12_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD12_checkBox)
        self.displayNodeDerivativeLabelsD13_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD13_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD13_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD13_checkBox.setObjectName("displayNodeDerivativeLabelsD13_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD13_checkBox)
        self.displayNodeDerivativeLabelsD23_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD23_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD23_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD23_checkBox.setObjectName("displayNodeDerivativeLabelsD23_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD23_checkBox)
        self.displayNodeDerivativeLabelsD123_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD123_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD123_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD123_checkBox.setObjectName("displayNodeDerivativeLabelsD123_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD123_checkBox)
        self.verticalLayout_13.addWidget(self.displayNodeDerivativeLabels_frame)
        self.displayLines_frame = QtGui.QFrame(self.display_tab)
        self.displayLines_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayLines_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayLines_frame.setObjectName("displayLines_frame")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.displayLines_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.displayLines_checkBox = QtGui.QCheckBox(self.displayLines_frame)
        self.displayLines_checkBox.setObjectName("displayLines_checkBox")
        self.horizontalLayout_5.addWidget(self.displayLines_checkBox)
        self.displayLinesExterior_checkBox = QtGui.QCheckBox(self.displayLines_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayLinesExterior_checkBox.sizePolicy().hasHeightForWidth())
        self.displayLinesExterior_checkBox.setSizePolicy(sizePolicy)
        self.displayLinesExterior_checkBox.setObjectName("displayLinesExterior_checkBox")
        self.horizontalLayout_5.addWidget(self.displayLinesExterior_checkBox)
        self.displayModelRadius_checkBox = QtGui.QCheckBox(self.displayLines_frame)
        self.displayModelRadius_checkBox.setObjectName("displayModelRadius_checkBox")
        self.horizontalLayout_5.addWidget(self.displayModelRadius_checkBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_13.addWidget(self.displayLines_frame)
        self.displaySurfaces_frame = QtGui.QFrame(self.display_tab)
        self.displaySurfaces_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displaySurfaces_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displaySurfaces_frame.setObjectName("displaySurfaces_frame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.displaySurfaces_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.displaySurfaces_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        self.displaySurfaces_checkBox.setObjectName("displaySurfaces_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfaces_checkBox)
        self.displaySurfacesExterior_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesExterior_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesExterior_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesExterior_checkBox.setObjectName("displaySurfacesExterior_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesExterior_checkBox)
        self.displaySurfacesTranslucent_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesTranslucent_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesTranslucent_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesTranslucent_checkBox.setObjectName("displaySurfacesTranslucent_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesTranslucent_checkBox)
        self.displaySurfacesWireframe_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesWireframe_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesWireframe_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesWireframe_checkBox.setObjectName("displaySurfacesWireframe_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesWireframe_checkBox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_13.addWidget(self.displaySurfaces_frame)
        self.displayElements_frame = QtGui.QFrame(self.display_tab)
        self.displayElements_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayElements_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayElements_frame.setObjectName("displayElements_frame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.displayElements_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.displayElementNumbers_checkBox = QtGui.QCheckBox(self.displayElements_frame)
        self.displayElementNumbers_checkBox.setObjectName("displayElementNumbers_checkBox")
        self.horizontalLayout_4.addWidget(self.displayElementNumbers_checkBox)
        self.displayElementAxes_checkBox = QtGui.QCheckBox(self.displayElements_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayElementAxes_checkBox.sizePolicy().hasHeightForWidth())
        self.displayElementAxes_checkBox.setSizePolicy(sizePolicy)
        self.displayElementAxes_checkBox.setObjectName("displayElementAxes_checkBox")
        self.horizontalLayout_4.addWidget(self.displayElementAxes_checkBox)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_13.addWidget(self.displayElements_frame)
        self.displayMisc_frame = QtGui.QFrame(self.display_tab)
        self.displayMisc_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayMisc_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayMisc_frame.setObjectName("displayMisc_frame")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.displayMisc_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.displayAxes_checkBox = QtGui.QCheckBox(self.displayMisc_frame)
        self.displayAxes_checkBox.setObjectName("displayAxes_checkBox")
        self.horizontalLayout_8.addWidget(self.displayAxes_checkBox)
        self.displayMarkerPoints_checkBox = QtGui.QCheckBox(self.displayMisc_frame)
        self.displayMarkerPoints_checkBox.setObjectName("displayMarkerPoints_checkBox")
        self.horizontalLayout_8.addWidget(self.displayMarkerPoints_checkBox)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_13.addWidget(self.displayMisc_frame)
        self.controls_tabWidget.addTab(self.display_tab, "")
        self.annotation_tab = QtGui.QWidget()
        self.annotation_tab.setObjectName("annotation_tab")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.annotation_tab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.annoptationModify_frame = QtGui.QFrame(self.annotation_tab)
        self.annoptationModify_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.annoptationModify_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.annoptationModify_frame.setObjectName("annoptationModify_frame")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.annoptationModify_frame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.annotationGroupNew_pushButton = QtGui.QPushButton(self.annoptationModify_frame)
        self.annotationGroupNew_pushButton.setObjectName("annotationGroupNew_pushButton")
        self.horizontalLayout_11.addWidget(self.annotationGroupNew_pushButton)
        self.annotationGroupRedefine_pushButton = QtGui.QPushButton(self.annoptationModify_frame)
        self.annotationGroupRedefine_pushButton.setObjectName("annotationGroupRedefine_pushButton")
        self.horizontalLayout_11.addWidget(self.annotationGroupRedefine_pushButton)
        self.annotationGroupDelete_pushButton = QtGui.QPushButton(self.annoptationModify_frame)
        self.annotationGroupDelete_pushButton.setObjectName("annotationGroupDelete_pushButton")
        self.horizontalLayout_11.addWidget(self.annotationGroupDelete_pushButton)
        self.verticalLayout_12.addWidget(self.annoptationModify_frame)
        self.annotationGroup_frame = QtGui.QFrame(self.annotation_tab)
        self.annotationGroup_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.annotationGroup_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.annotationGroup_frame.setObjectName("annotationGroup_frame")
        self.formLayout_2 = QtGui.QFormLayout(self.annotationGroup_frame)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.annotationGroup_label = QtGui.QLabel(self.annotationGroup_frame)
        self.annotationGroup_label.setObjectName("annotationGroup_label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.annotationGroup_label)
        self.annotationGroup_comboBox = QtGui.QComboBox(self.annotationGroup_frame)
        self.annotationGroup_comboBox.setObjectName("annotationGroup_comboBox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.annotationGroup_comboBox)
        self.annotationGroupOntId_label = QtGui.QLabel(self.annotationGroup_frame)
        self.annotationGroupOntId_label.setObjectName("annotationGroupOntId_label")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.annotationGroupOntId_label)
        self.annotationGroupOntId_lineEdit = QtGui.QLineEdit(self.annotationGroup_frame)
        self.annotationGroupOntId_lineEdit.setObjectName("annotationGroupOntId_lineEdit")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.annotationGroupOntId_lineEdit)
        self.annotationGroupDimension_label = QtGui.QLabel(self.annotationGroup_frame)
        self.annotationGroupDimension_label.setObjectName("annotationGroupDimension_label")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.annotationGroupDimension_label)
        self.annotationGroupDimension_spinBox = QtGui.QSpinBox(self.annotationGroup_frame)
        self.annotationGroupDimension_spinBox.setMinimum(0)
        self.annotationGroupDimension_spinBox.setMaximum(3)
        self.annotationGroupDimension_spinBox.setProperty("value", 0)
        self.annotationGroupDimension_spinBox.setObjectName("annotationGroupDimension_spinBox")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.annotationGroupDimension_spinBox)
        self.verticalLayout_12.addWidget(self.annotationGroup_frame)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem9)
        self.controls_tabWidget.addTab(self.annotation_tab, "")
        self.verticalLayout.addWidget(self.controls_tabWidget)
        self.bottom_frame = QtGui.QFrame(self.dockWidgetContents)
        self.bottom_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewAll_pushButton = QtGui.QPushButton(self.bottom_frame)
        self.viewAll_pushButton.setObjectName("viewAll_pushButton")
        self.horizontalLayout_2.addWidget(self.viewAll_pushButton)
        self.stdViews_pushButton = QtGui.QPushButton(self.bottom_frame)
        self.stdViews_pushButton.setObjectName("stdViews_pushButton")
        self.horizontalLayout_2.addWidget(self.stdViews_pushButton)
        self.done_pushButton = QtGui.QPushButton(self.bottom_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done_pushButton.sizePolicy().hasHeightForWidth())
        self.done_pushButton.setSizePolicy(sizePolicy)
        self.done_pushButton.setObjectName("done_pushButton")
        self.horizontalLayout_2.addWidget(self.done_pushButton)
        self.verticalLayout.addWidget(self.bottom_frame)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.sceneviewer_widget = NodeEditorSceneviewerWidget(MeshGeneratorWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewer_widget.sizePolicy().hasHeightForWidth())
        self.sceneviewer_widget.setSizePolicy(sizePolicy)
        self.sceneviewer_widget.setObjectName("sceneviewer_widget")
        self.horizontalLayout.addWidget(self.sceneviewer_widget)

        self.retranslateUi(MeshGeneratorWidget)
        self.controls_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MeshGeneratorWidget)

    def retranslateUi(self, MeshGeneratorWidget):
        MeshGeneratorWidget.setWindowTitle(QtGui.QApplication.translate("MeshGeneratorWidget", "Mesh Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MeshGeneratorWidget", "Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.identifier_label.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Identifier", None, QtGui.QApplication.UnicodeUTF8))
        self.subscaffold_label.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Subscaffold", None, QtGui.QApplication.UnicodeUTF8))
        self.subscaffoldBack_pushButton.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "<< Back", None, QtGui.QApplication.UnicodeUTF8))
        self.meshType_label.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Mesh type:", None, QtGui.QApplication.UnicodeUTF8))
        self.parameterSet_label.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Parameter set:", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteElementsRanges_label.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Delete element ID ranges (e.g. 1,2-5,13):", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteElementsSelection_pushButton.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Delete selected elements", None, QtGui.QApplication.UnicodeUTF8))
        self.rotation_label.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Rotation in degrees about z, y, x", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_label.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Scale x, y, z:", None, QtGui.QApplication.UnicodeUTF8))
        self.translation_label.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Translation x, y, z", None, QtGui.QApplication.UnicodeUTF8))
        self.applyTransformation_pushButton.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Apply transformation", None, QtGui.QApplication.UnicodeUTF8))
        self.displayDataPoints_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Data points", None, QtGui.QApplication.UnicodeUTF8))
        self.displayDataContours_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Data contours", None, QtGui.QApplication.UnicodeUTF8))
        self.displayDataRadius_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Data radius", None, QtGui.QApplication.UnicodeUTF8))
        self.displayDataMarkerPoints_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Data marker points", None, QtGui.QApplication.UnicodeUTF8))
        self.displayDataMarkerNames_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Data marker names", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodePoints_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Node points", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeNumbers_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Node numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivatives_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Node derivatives", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD1_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "D1", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD2_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "D2", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD3_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "D3", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD12_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "D12", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD13_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "D13", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD23_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "D23", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD123_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "D123", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLines_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLinesExterior_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Exterior", None, QtGui.QApplication.UnicodeUTF8))
        self.displayModelRadius_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Model radius", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfaces_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Surfaces", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesExterior_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Exterior", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesTranslucent_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Transluc.", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesWireframe_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Wireframe", None, QtGui.QApplication.UnicodeUTF8))
        self.displayElementNumbers_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Element numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.displayElementAxes_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Element axes", None, QtGui.QApplication.UnicodeUTF8))
        self.displayAxes_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.displayMarkerPoints_checkBox.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Marker points", None, QtGui.QApplication.UnicodeUTF8))
        self.controls_tabWidget.setTabText(self.controls_tabWidget.indexOf(self.display_tab), QtGui.QApplication.translate("MeshGeneratorWidget", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationGroupNew_pushButton.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationGroupRedefine_pushButton.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Redefine", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationGroupDelete_pushButton.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationGroup_label.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Group:", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationGroupOntId_label.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "ONT:ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationGroupDimension_label.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Dimension:", None, QtGui.QApplication.UnicodeUTF8))
        self.controls_tabWidget.setTabText(self.controls_tabWidget.indexOf(self.annotation_tab), QtGui.QApplication.translate("MeshGeneratorWidget", "Annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAll_pushButton.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.stdViews_pushButton.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Std. Views", None, QtGui.QApplication.UnicodeUTF8))
        self.done_pushButton.setText(QtGui.QApplication.translate("MeshGeneratorWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))

from mapclientplugins.meshgeneratorstep.view.nodeeditorsceneviewerwidget import NodeEditorSceneviewerWidget
from mapclientplugins.meshgeneratorstep import resources_rc
